### ISSUE TITLE
MicroPCF becoming unavailable after laptop sleep (Mac OS X)

### ISSUE THREAD

**Issue by davidillsley** [vmware-archive/pcfdev#36] opened 2016-02-26 11:08 UTC
With MicroPCF v0.6.0, I'm intermittently seeing the instance fail when my laptop returns from sleep. Vagrant reports the VM to be healthy, but the API and apps are unavailable.

VirtualBox Version 5.0.14 r105127
Vagrant 1.8.1
MicroPCF v0.6.0
OSX 10.11.3

**Comment by openjack** [comment] 2016-02-26 14:17
I'm seeing the same thing.

**Comment by echurchm** [comment] 2016-02-27 23:27
My problem is similar.   When I restart my VM, it does not come up on 192.168.11.11 anymore  so the Apps and API are not available.  I am even using the environment variable to set it.

**Comment by Turbots** [comment] 2016-03-02 00:08
I had the same issues with the Lattice configuration on my Mac (El Capitan). I had to do

`vagrant reload`

to fix the problem. I think the network interface gets permanently disconnected but I'm no networking wizz :-)

**Comment by sclevine** [comment] 2016-04-15 02:25
This has been fixed in the [latest version of PCF Dev](https://network.pivotal.io/products/pcfdev).

This was caused by CPU soft lockups in Virtualbox triggered by the `kvm-clock` kernel clock source. To resolve the issue, we switched to the `minimal` Virtualbox paravirtualization mode, which does not support that clock source. Feel free to re-open if you're still experiencing this issue.

**Closed as completed by sclevine** 2016-04-15 02:25 UTC
