### ISSUE TITLE
pcf dev 0.18 fail to start p-circuit-breaker-dashboard service instance

### ISSUE THREAD

**Issue by clfsoft** [vmware-archive/pcfdev#117] opened 2016-08-03 04:28 UTC
CF:
 cf version 6.20.0+25b1961-2016-06-29
 PCF Dev version 0.18.0 (CLI: 5c9e186, OVA: 0.219.0)
OS: windows 7 sp1 x64  
VM: VirtualBox 5.0.24

p-config-server and p-service-registry work as expected
but when i create a  p-circuit-breaker-dashboard service instance

> Service "dashboard-server" was created, but failed to bind to "hello3". Service broker error: Service instance is not running and available for binding.

found  org p-spring-cloud-services is  the place where the service instance reside
hystrix-XXXX app and turbine-XXX fail to start with the log

> 2016-08-03T13:07:41.580+09:00 [API] [OUT] Created app with guid ba022af5-58ef-436a-8ee7-bae02e06e3b8
> 2016-08-03T13:07:42.198+09:00 [API] [OUT] Updated app with guid ba022af5-58ef-436a-8ee7-bae02e06e3b8 ({"route"=>"cc3aefd0-1fa5-4dce-85e1-e28d7475f05a"})
> 2016-08-03T13:07:42.358+09:00 [API] [OUT] Updated app with guid ba022af5-58ef-436a-8ee7-bae02e06e3b8 ({"environment_json"=>"PRIVATE DATA HIDDEN"})
> 2016-08-03T13:07:42.479+09:00 [API] [OUT] Updated app with guid ba022af5-58ef-436a-8ee7-bae02e06e3b8 ({"instances"=>1})
> 2016-08-03T13:07:49.648+09:00 [API] [OUT] Updated app with guid ba022af5-58ef-436a-8ee7-bae02e06e3b8 ({"state"=>"STARTED"})
> ......
> 2016-08-03T13:07:49.670+09:00 [STG] [OUT] Downloading binary_buildpack...
>  [API] [ERR] Failed to stage application: staging failed

then I manually start these two apps  under  org p-spring-cloud-services / space instances
and try to bind the p-circuit-breaker-dashboard service instance  
and fail with the message

> Service broker error: Service instance failed to start.

any clue will be appreciated

**Comment by clfsoft** [comment] 2016-08-03 06:54
found the error in  spring-cloud-broker and spring-cloud-broker-worker  apps logs

> Execution took longer than 180000 MILLISECONDS

how to change the timeout value  ?

**Comment by clfsoft** [comment] 2016-08-03 08:12
is following file to  change the timeout value

> /var/vcap/jobs/deploy-service-broker/bin/run
> export BROKER_APP_NAME=spring-cloud-broker
> export APP_PUSH_TIMEOUT=180
> export APP_PUSH_MEMORY=1024m
> export PERSISTENCE_STORE_TYPE=mysql
> export MESSAGE_BUS_TYPE=rabbitmq
> export BUILDPACK=

**Comment by sclevine** [comment] 2016-08-04 14:15
Hi @clfsoft,

Thanks for the report! Did changing that value fix the issue for you? After changing it, you can reboot the VM with `cf dev stop` followed by `cf dev start`.

-Stephen

**Comment by clfsoft** [comment] 2016-08-04 14:50
not work. the enviroment value is for the spring-cloud-broker deployment .
but when I check the spring cloud  service broker deployment script,
 I found an environment  variable SCS_BUILDPACK which should be used to deploy the service instances

so I will try the solution from 
 [https://support.run.pivotal.io/entries/25236493-Pushing-large-Java-based-applications-to-CloudFoundry](url) 

which will fork a java_buildpack and change the server.xml's  property bindOnInit to true
then point  SCS_BUILDPACK to my forked java_buildpack

**Comment by clfsoft** [comment] 2016-08-05 05:21
no luck. the staging time is over 180s. 
so there is not enough time for the workaround to come into play.

**Comment by mdelillo** [comment] 2016-08-08 15:35
Hi @clfsoft, this looks like a known issue around staging timeouts. This should be fixed in the next release.

**Comment by sclevine** [comment] 2016-09-22 19:00
Should be fixed in 0.20.0. Please re-open if you continue to experience this issue.

**Closed as completed by sclevine** 2016-09-22 19:00 UTC
Labels: bug

**Comment by clfsoft** [comment] 2016-11-07 09:53
@sclevine 
@mdelillo  
not worked still same error at 0.21.0.

according to the flowing document. the spring cloud service broker worker implmentation is flawed.

https://docs.cloudfoundry.org/devguide/deploy-apps/large-app-deploy.html
[Because of the differences between the Cloud Foundry and cf CLI timeout values, your app might **successfully start even though the cf CLI reports App failed**. Run cf apps APP_NAME to review the actual status of your app.]

And I encounter the same issue with PCF on AWS.

**Comment by ksatyajitpatra** [comment] 2017-01-26 22:07
Hello,
I am on "PCF Dev version 0.23.0 (CLI: 474b3ba, OVA: 0.436.0)". I am able to create config server & service registry service instances but not able create a service instance for circuit breaker dashboard. I tried few times but it is failing with status as "create failed". Can anyone help with debugging the root cause of this?

**Comment by sclevine** [comment] 2017-01-26 22:10
Hi @ksatyajitpatra,

Can you provide the output of `cf dev start -s scs`?
Is it possible that your VM has run out of memory?

Occasionally, I've seen failures when attempting to create multiple service instances simultaneously.

**Comment by ksatyajitpatra** [comment] 2017-01-27 01:35
Hi Stephen,

Please see below for the details.

--------------

C:\Users\satyajit.patra>cf dev start -s all
$B"+(B[31;1mFAILED$B"+(B[0m
Error: services cannot be changed once the vm has been created.

C:\Users\satyajit.patra>cf dev start -s scs
$B"+(B[31;1mFAILED$B"+(B[0m
Error: services cannot be changed once the vm has been created.

C:\Users\satyajit.patra>cf dev start
Using existing image.
Starting VM...
Provisioning VM...
Waiting for services to start...
9 out of 57 running
9 out of 57 running
9 out of 57 running
40 out of 57 running
57 out of 57 running
 _______  _______  _______    ______   _______  __   __
|       ||       ||       |  |      | |       ||  | |  |
|    _  ||       ||    ___|  |  _    ||    ___||  |_|  |
|   |_| ||       ||   |___   | | |   ||   |___ |       |
|    ___||      _||    ___|  | |_|   ||    ___||       |
|   |    |     |_ |   |      |       ||   |___  |     |
|___|    |_______||___|      |______| |_______|  |___|
is now running.
To begin using PCF Dev, please run:
   cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Apps Manager URL: https://local.pcfdev.io
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass

C:\Users\satyajit.patra>cf marketplace
Getting services from marketplace in org pcfdev-org / space pcfdev-space as admi
n...
OK

service                       plans             description
local-volume                  free-local-disk   Local service docs: https://gith
ub.com/cloudfoundry-incubator/local-volume-release/
p-circuit-breaker-dashboard   standard          Circuit Breaker Dashboard for Sp
ring Cloud Applications
p-config-server               standard          Config Server for Spring Cloud A
pplications
p-mysql                       512mb, 1gb        MySQL databases on demand
p-rabbitmq                    standard          RabbitMQ is a robust and scalabl
e high-performance multi-protocol messaging broker.
p-redis                       shared-vm         Redis service to provide a key-v
alue store
p-service-registry            standard          Service Registry for Spring Clou
d Applications

TIP:  Use 'cf marketplace -s SERVICE' to view descriptions of individual plans o
f a given service.
---------------


Thank you,

K. Satyajit Patra

________________________________

**Comment by mdelillo** [comment] 2017-01-30 23:01
@ksatyajitpatra did you mean to post that to #192?
