### ISSUE TITLE
Unable to install pcfdev plugin

### ISSUE THREAD

**Issue by AubieDawg92** [vmware-archive/pcfdev#250] opened 2017-07-31 18:00 UTC
Windows Version: Windows 7 Enterprise SP1
CLI version: cf.exe version 6.29.0+ff886fa.2017-07-24
PCF Dev: pcfdev-v0.26.0+PCF1.10.0-windows.exe

I am attempting to install PCF DEV as shown below.  I have seen other issues with the same behavior which pointed to a _possible_ local firewall issue.  All of those issues were closed without a definitive resolution.  I am fairly confident that I do not have a firewall issue.  I started netmon and tried setting some proxy configurations and I never see any traffic being attempted on the port listed in the error message (which changes with every attempt). 

`PS C:\pcf> cf install-plugin .\pcfdev-v0.26.0+PCF1.10.0-windows.exe`
`Attention: Plugins are binaries written by potentially untrusted authors.`
`Install and use plugins at your own risk.`
`Do you want to install the plugin .\pcfdev-v0.26.0+PCF1.10.0-windows.exe? [yN]: y`
`y`
`dial tcp 127.0.0.1:49299: socket: An invalid argument was supplied.`
`exit status 1`
`File is not a valid cf CLI plugin binary.`
`FAILED`

Any help is appreciated.

**Comment by sclevine** [comment] 2017-07-31 18:19
This looks like a duplicate of #248. This is not an issue with PCF Dev. Please follow the issue [upstream](https://github.com/cloudfoundry/cli/issues/1184).

**Closed as completed by sclevine** 2017-07-31 18:19 UTC
Labels: accepted

**Comment by AubieDawg92** [comment] 2017-07-31 18:27
There is no resolution listed for any upstream issue.  As I mentioned, I am pretty confident that there is NOT a firewall issue.  There is no documentation, that I could find, that pointed to required ports being opened.  If this is all local to the machine, then that shouldn't be an issue anyway.  Is there possibly some other required prerequisite that is needed that isn't listed in the documentation?

**Comment by sclevine** [comment] 2017-07-31 18:56
Again, this issue affects all cf CLI plugins, not just PCF Dev. The cf CLI needs to be able to bind to ports on the local loopback device in order to install and run plugins. This is not working on your machine, for an unknown reason.

The upstream issue is currently in-flight: https://www.pivotaltracker.com/n/projects/892938/stories/149303367
This means that engineers are likely actively looking into what system configuration could cause this problem on Windows 7.
