### ISSUE TITLE
pcfdev login error

### ISSUE THREAD

**Issue by vcherukuri** [vmware-archive/pcfdev#105] opened 2016-07-19 10:54 UTC
I am trying to deploy pcfdev on a Microsoft Azure Windows VM. Installed cf CLI, Oracle Virtual Box and pcfdev plugin. when i tried cf dev start the pcfdev is created and started in Virtual box. But when i tried connecting cf login -a https://api.local.pcfdev.io --skip-ssl-validation it is not connecting.

ipconfig shows me that a pcfdev VM is created with IP 192.168.11.1.

I could ping to 192.168.11.1, so I changed the \etc\hosts to point api.local.pcfdev.io to 192.168.11.1 and i could ping api.local.pcfdev.io. i tried https_proxy, no_proxy set to api.local.pcfdev.io. but still cf login doesnt work.
please suggest

**Comment by sclevine** [comment] 2016-07-19 13:31
Hi @vcherukuri,

In #106, you indicated that your VM did not start completely. Can you provide the output of `cf dev start`?

Also, it should not be necessary to add `/etc/hosts` entries to run PCF Dev. `*.local.pcfdev.io` resolution is handled by our DNS servers. Setting `https_proxy` to `api.local.pcfdev.io` will definitely prevent `cf login` from working, because `api.local.pcfdev.io` is not an HTTPS proxy server.

**Comment by vcherukuri** [comment] 2016-07-20 13:39
tried installing pcfdev on Azure linux VM:

```
Downloading VM...
Progress: |====================>| 100%
VM downloaded
Allocating 3484 MB out of 6968 MB total system memory (6614 MB free).
Importing VM...
FAILED
Error: failed to import VM: failed to execute 'VBoxManage clonemedium disk /home/pcf/.pcfdev/vms/pcfdev-v0.136.0-disk1.vmdk.compressed /home/pcf/.pcfdev/vms/pcfdev-v0.136.0/pcfdev-v0.136.0-disk1.vmdk': exit status 1: VBoxManage: error: Could not get the storage format of the medium '/home/pcf/.pcfdev/vms/pcfdev-v0.136.0-disk1.vmdk.compressed' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
```

**Comment by vcherukuri** [comment] 2016-07-20 13:47
Is this a problem with the virtual box software? Any suggestions on which version of virtual box and pcfdev to be used for a successful installation on Microsoft Azure virtual Machine.

**Comment by sclevine** [comment] 2016-07-20 13:51
As mentioned in [the docs](https://docs.pivotal.io/pcf-dev/), you must use Virtualbox 5+ to run PCF Dev. Your Linux run of  `cf dev start` was likely using an older version of Virtualbox.

I would need to see the boot output on the Windows VM to diagnose the issue you're having on Windows.

**Comment by vcherukuri** [comment] 2016-07-20 14:19
but the virtual box version i am using is virtualbox-5.1

**Comment by sclevine** [comment] 2016-07-20 14:25
Is it possible that you're running out free disk space on the VM?

If not, could you downgrade to Virtualbox 5.0.24? Preliminary testing suggests that PCF Dev works with Virtualbox 5.1, but we haven't tested it as extensively as 5.0.

**Comment by vcherukuri** [comment] 2016-07-21 06:10
Tried with Virtual box 5.0.24 but pcfdev vm cannot be started

```
cf dev start
Please retrieve your Pivotal Network API from:
https://network.pivotal.io/users/dashboard/edit-profile

API token>
Downloading VM...
Progress: |====================>| 100%
VM downloaded
Allocating 4096 MB out of 14024 MB total system memory (13718 MB free).
Importing VM...
Starting VM...
FAILED
Error: failed to start VM: failed to execute 'VBoxManage startvm pcfdev-v0.136.0                                                                                         --type headless': exit status 1: VBoxManage: error: VT-x is not available (VERR                                                                                        _VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component Consol                                                                                        eWrap, interface IConsole
Waiting for VM "pcfdev-v0.136.0" to power on...

 vboxmanage -version
5.0.24r108355
vboxmanage list vms
"pcfdev-v0.136.0" {306c4ae7-81e6-452a-8082-82f083c5bb64}
```

**Comment by sclevine** [comment] 2016-07-21 14:07
Hi @vcherukuri,

Is that boot output from a different VM? The error indicates that you don't have VT-x passthrough enabled on the VM that you're starting PCF Dev in. You will not be able to virtualize any VMs (including PCF Dev) inside of a VM configured without VT-x passthrough.

**Comment by delormej** [comment] 2016-07-21 14:32
I've made it possibly a little further in the sense that I have Virtual Box running on an Ubuntu VM on Azure and have got it to start the VM through pcf dev start, but fails when trying to connect via ssh.

I'm running Ubuntu 16.04 LTS on an Standard DS1 v2 (1 core, 3.5 GB memory).

```
$ vboxmanage --version
5.0.24_Ubuntur108355

$cf dev start
...
Importing VM...
Starting VM...
FAILED
**Error: failed to start VM: ssh connection timed out: ssh: handshake failed: read tcp 127.0.0.1:33680->127.0.0.1:39564: read: connection reset by peer**

Showing VM info, it looks like it's using NAT for networking, but the port isn't getting forwarded or something is getting lost... when I try to manually ssh, same thing happens:

$ ssh 127.0.0.1 -p 39564
ssh_exchange_identification: read: Connection reset by peer


$ vboxmanage showvminfo pcfdev-v0.136.0
Name:            pcfdev-v0.136.0
Groups:          /
Guest OS:        Ubuntu (64-bit)
UUID:            09d8f526-5aea-4e9d-8423-0723b33976c7
Config file:     /home/jason/.pcfdev/vms/pcfdev-v0.136.0/pcfdev-v0.136.0.vbox
Snapshot folder: /home/jason/.pcfdev/vms/pcfdev-v0.136.0/Snapshots
Log folder:      /home/jason/.pcfdev/vms/pcfdev-v0.136.0/Logs
Hardware UUID:   09d8f526-5aea-4e9d-8423-0723b33976c7
Memory size:     3072MB
Page Fusion:     off
VRAM size:       8MB
CPU exec cap:    100%
HPET:            off
Chipset:         piix3
Firmware:        BIOS
Number of CPUs:  1
PAE:             on
Long Mode:       on
CPUID Portability Level: 0
CPUID overrides: None
Boot menu mode:  message and menu
Boot Device (1): Floppy
Boot Device (2): DVD
Boot Device (3): HardDisk
Boot Device (4): Not Assigned
ACPI:            on
IOAPIC:          on
Time offset:     0ms
RTC:             local time
Hardw. virt.ext: on
Nested Paging:   on
Large Pages:     off
VT-x VPID:       on
VT-x unr. exec.: on
Paravirt. Provider: Default
State:           running (since 2016-07-21T13:34:36.142000000)
Monitor count:   1
3D Acceleration: off
2D Video Acceleration: off
Teleporter Enabled: off
Teleporter Port: 0
Teleporter Address:
Teleporter Password:
Tracing Enabled: off
Allow Tracing to Access VM: off
Tracing Configuration:
Autostart Enabled: off
Autostart Delay: 0
Default Frontend:
Storage Controller Name (0):            SATA
Storage Controller Type (0):            IntelAhci
Storage Controller Instance Number (0): 0
Storage Controller Max Port Count (0):  30
Storage Controller Port Count (0):      30
Storage Controller Bootable (0):        on
SATA (0, 0): /home/jason/.pcfdev/vms/pcfdev-v0.136.0/pcfdev-v0.136.0-disk1.vmdk (UUID: 8913ad9b-53dd-4fba-9af8-fb65756ddb9a)
NIC 1:           MAC: 0800276635D8, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)
NIC 1 Rule(0):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 39564, guest ip = , guest port = 22
NIC 2:           MAC: 080027C1B7C1, Attachment: Host-only Interface 'vboxnet0', Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 3:           disabled
NIC 4:           disabled
NIC 5:           disabled
NIC 6:           disabled
NIC 7:           disabled
NIC 8:           disabled
Pointing Device: PS/2 Mouse
Keyboard Device: PS/2 Keyboard
UART 1:          disabled
UART 2:          disabled
UART 3:          disabled
UART 4:          disabled
LPT 1:           disabled
LPT 2:           disabled
Audio:           disabled
Clipboard Mode:  disabled
Drag and drop Mode: disabled
Session name:    headless
Video mode:      640x480x32 at 0,0 enabled
VRDE:            disabled
USB:             disabled
EHCI:            disabled
XHCI:            disabled

USB Device Filters:

<none>

Available remote USB devices:

<none>

Currently Attached USB Devices:

<none>

Bandwidth groups:  <none>

Shared folders:  <none>

VRDE Connection:    not active
Clients so far:     0

Video capturing:    not active
Capture screens:    0
Capture file:       /home/jason/.pcfdev/vms/pcfdev-v0.136.0/pcfdev-v0.136.0.webm
Capture dimensions: 1024x768
Capture rate:       512 kbps
Capture FPS:        25

Guest:

Configured memory balloon size:      0 MB
OS type:                             Ubuntu_64
Additions run level:                 0

Guest Facilities:

No active facilities.
```

**Comment by sclevine** [comment] 2016-07-21 14:42
Hi @delormej,

Your host VM has well below the recommended system memory to run PCF Dev. Virtualbox seems able to reserve 3 GB of memory for the guest, but could you be running out of memory on the host?

**Comment by delormej** [comment] 2016-07-21 14:48
I will try a bigger VM, I do get this message when deploying:
Allocating 3072 MB out of 3439 MB total system memory (3195 MB free).

```
  From: Stephen Levine <notifications@github.com>
```

 To: pivotal-cf/pcfdev pcfdev@noreply.github.com 
Cc: delormej jjdelorme@yahoo.com; Mention mention@noreply.github.com
 Sent: Thursday, July 21, 2016 10:42 AM
 Subject: Re: [pivotal-cf/pcfdev] pcfdev login error (#105)

Hi @delormej,Your host VM has well below the recommended system memory to run PCF Dev. Virtualbox seems able to reserve 3 GB of memory for the guest, but could you be running out of memory on the host?—

**Comment by delormej** [comment] 2016-07-21 15:06
@sclevine upgraded to a Standard DS2 v2 (2 cores, 7 GB memory), same issue.  I do believe that the issue is related to virtual box networking.  Would it terrifically break things if I changed from NAT to another networking type? Something funky is happening.  

images/pcfdev.json 
 [ "modifyvm", "{{.Name}}", "--nic1", "nat" ],

Thanks!

**Comment by sclevine** [comment] 2016-07-25 14:35
Changing the networking type could easily break things. (I haven't tried it though.)

Is it possible that you have restrictive iptables rules (manually set, or from a firewall program) that prevent Virtualbox from binding the guest SSH port to a host port?

Also, this issue seems similar to #97.

**Comment by Mahesh0310** [comment] 2016-08-04 06:40
Dear sclevine
I am also trying PCF Dev on Azure.  I was going through the blog inline with your and @vcherukuri , is the issue resolved with not able to login, pl. let me know the same.

**Comment by Mahesh0310** [comment] 2016-08-08 03:55
Any reply on the same, pl. let me know the same.

**Comment by eduardohl** [comment] 2016-08-10 17:57
Hi,

I'm having the same issue using VirtualBox 5.1.2

When I start the VM everything goes well:

is now running.
To begin using PCF Dev, please run:
cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass

But when I try to login (from the local machine, not inside the vm)
I get:
API endpoint: api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp: lookup api.local.pcfdev.io on 127.0.0.1:53: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

I logged to vagrant@192.168.11.11 and found this in the end of /var/pcfdev/run.log:
- cf unmap-route apps-manager-venerable local.pcfdev.io --hostname apps-manager
  FAILED
  App apps-manager-venerable not found
  - true
  - cf unmap-route apps-manager-venerable local.pcfdev.io --hostname console --path /2
    FAILED
    App apps-manager-venerable not found

Everything else seems fine. Any advice on how to proceed? Should I be trying to log to the client from inside the virtual box vm (instead of my host machine)?

**Comment by sclevine** [comment] 2016-08-10 18:06
@eduardohl Your issue does not seem similar to the opening issue. Are you also attempting to run PCF Dev on Azure? Are you able to resolve `api.local.pcfdev.io` to `192.168.11.11` on your host machine? It seems like your VM is fine, but your host cannot resolve that domain.

**Comment by eduardohl** [comment] 2016-08-10 18:19
Not so similar, in a sense that's not Azure, but I thought the networking problem is similar. No I'm not able to resolve api.local.pcfdev.io, even thought I tried changing the DNS servers to 8.8.8.8 and that didn't help. Finally, I seem to be able to do it by following this section: https://docs.pivotal.io/pcf-dev/work-offline.html
I'm still curious to understand how would it work in any other fashion. Hope this is related to this issue, otherwise I can delete it to avoid cluttering it.

**Comment by sclevine** [comment] 2016-08-10 18:40
The `*.local.pcfdev.io` resolution is provided by our public DNS servers. The `api.local.pcfdev.io` domain should resolve to `192.168.11.11` on any host that can resolve public DNS domains (ex. `example.com`).

**Comment by sclevine** [comment] 2016-09-22 19:04
The team has confirmed that Azure does not support VT-x, and therefore cannot run PCF Dev nested in Virtualbox. Please open new issues for problems unrelated to Azure.

**Closed as completed by sclevine** 2016-09-22 19:04 UTC
Labels: help wanted

**Comment by abhijitpatil1009** [comment] 2017-03-02 08:37
Hi SClevine,
I am facing same issue-cf dev start Failed, I am installing CFdev on windows10  machine
Downloading VM...
Progress: |====================>| 100%
VM downloaded.
Allocating 3575 MB out of 7150 MB total system memory (3197 MB free).
Importing VM...
Starting VM...
FAILED
Error: failed to start VM: ssh connection timed out: ssh: handshake failed: read tcp 127.0.0.1:60481->127.0.0.1:60422: wsarecv: An existing connection was forcibly closed by the remote host..

Please Help
Thanks a lot !
Abhijit patil.

**Comment by sclevine** [comment] 2017-03-02 15:39
As mentioned in #200, you are likely trying to virtualize PCF Dev in a nested VM that doesn't support VT-x.

**Comment by kpurushottamfromdel** [comment] 2017-07-12 06:52
Hi,

When i am trying to run command cf dev start receiving below error.
Using existing image.
Allocating 4096 MB out of 16205 MB total system memory (9803 MB free).
Importing VM...
Starting VM...
FAILED
Error: failed to start VM: failed to execute 'C:\Program Files\Oracle\VirtualBox\VBoxManage startvm pcfdev-v0.461.0 --ty
pe headless': exit status 1: Waiting for VM "pcfdev-v0.461.0" to power on...
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole



And when i am starting VM from Oracle VM VirtualBox manager getting error:
Failed to open session for the VM .
VT-x is not available (VERR_VMX_NO_VMX).
Result Code: | E_FAIL (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by sclevine** [comment] 2017-07-12 14:32
Hi @kpurushottamfromdel,

You are attempting to start PCF Dev nested inside of another VM, or on a machine that does not support the VT-x processor extension. The VT-x processor extension is required to run 64-bit VMs in Virtualbox (such as the PCF Dev VM).
