### ISSUE TITLE
Hyper-V Support

### ISSUE THREAD

**Issue by wayne** [vmware-archive/pcfdev#307] opened 2018-03-07 15:35 UTC
With Docker for Windows now switching to Hyper-V, can we get a pcf-dev version using Hyper-V instead of Virtualbox.

**Comment by sclevine** [comment] 2018-03-07 15:56
Duplicate of #168. Hyper-V support (as well as support for BOSH) will be implemented when we switch the implementation of PCF Dev to use the new [CF Dev](https://github.com/pivotal-cf/cfdev).

**Closed as completed by sclevine** 2018-03-07 15:56 UTC
Labels: accepted
