### ISSUE TITLE
PCF-DEV 0.17.0 login issue

### ISSUE THREAD

**Issue by sridharpaladugu** [vmware-archive/pcfdev#88] opened 2016-06-29 16:51 UTC
installed PCF0.17.0 on osx and i am not able login to cf.  Here is the output. Any help?

[12:29]  
SridarPaduguMBP:PCF_DEV spaladugu$ cf dev start

Using existing image
Starting VM...
Provisioning VM...
Waiting for services to start...
50 out of 50 running
pcfdev
is now running.
To begin using PCF Dev, please run:
    cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass
SridarPaduguMBP:PCF_DEV spaladugu$  cf login -a https://api.local.pcfdev.io --skip-ssl-validation
API endpoint: https://api.local.pcfdev.io
FAILED
Error performing request: Get https://api.local.pcfdev.io/v2/info: dial tcp 192.168.11.11:443: connect: host is down
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

**Comment by sridharpaladugu** [comment] 2016-06-29 16:51
Tried the below as per Stephen Levine;

`cf dev destroy && sudo ifconfig vboxnet0 delete && sudo ifconfig vboxnet4 delete && cf dev start`

and that worked to get pass the login error.

**Comment by sclevine** [comment] 2016-06-29 21:16
We were not able to replicate this, but we believe it's caused by a bug in 0.16.0 that could result in multiple vboxnetX interfaces allocated to the same PCF Dev subnet. The 0.17.0 release fixes this bug, but will use the broken, conflicting interfaces created by 0.16.0. We're going to cut an 0.17.1 release soon that accounts for this situation.

In the meantime, rebooting your host or deleting the offending vboxnet interfaces with `sudo ifconfig vboxnetX delete` will allow you to work around the issue.

**Comment by sclevine** [comment] 2016-07-07 14:31
Fixed in the latest release candidate.

**Closed as completed by sclevine** 2016-07-07 14:31 UTC
Labels: bug

**Comment by vcherukuri** [comment] 2016-07-19 10:15
I am trying to deploy pcfdev on a Microsoft Azure Windows VM. Installed cf CLI, Oracle Virtual Box and pcfdev plugin. when i tried cf dev start the pcfdev is created and started in Virtual box. But when i tried connecting cf login -a https://api.local.pcfdev.io --skip-ssl-validation it is not connecting.

 ipconfig shows me that a pcfdev VM is created with IP 192.168.11.1.  
 I could ping to 192.168.11.1, so I changed the \etc\hosts to point api.local.pcfdev.io to 192.168.11.1 and i could ping api.local.pcfdev.io.  i tried https_proxy, no_proxy set to api.local.pcfdev.io. but still cf login doesnt work.
please suggest

**Comment by sclevine** [comment] 2016-07-19 13:28
@vcherukuri Let's address this in #105.
